import java.util.Scanner;


class Roman  {

   //Roman reads Roman Numerals generated by the user and converts them
   //to Arabic(integer) form 
    
    public static void main (String [] args)  {
	

 	//Accepts user input
	//passes String s to method romanToInt();
	//Prints out return statement 'foo'.
        
        Scanner keyboard = new Scanner(System.in); 
        
        System.out.println("Please write a Roman Numeral: ");
        
        String s = keyboard.nextLine();
        
        int foo = romanToInt(s);
        System.out.println(foo);
        
        
    }
    
	//method romanToInt() accepts String s
	//Declares variable foo at 0
	//uses 'for' loop to pass character by character through length of string
	//using charAt() method, evaluates each character according to values of 
	//Roman Numerals and translates the letter to that int value,
	//then passes that value to foo
    
    public static int romanToInt(String s)  {
        
        int foo = 0;
	
        
        for (int i = 0; i < s.length(); i ++)  {

	char j = s.charAt(i);
            
            if (j == 'M')  {
                
                foo += 1000;

                
            } else if (j == 'D' && s.charAt(i-1) == 'C')  {
                
                foo += 300;

                
            }  else if (j == 'D' && s.charAt(i-1) != 'C') {
                
                foo += 500;
                
            }  else if (j == 'C')  {
                
                foo += 100;
                
            }  else if (j == 'L')  {
                
                foo += 50;

	    //'&&' used to accommodate exceptions in evaluation  

            } else if (j == 'X' && s.charAt(i-1) == 'I')  {
               
                foo += 8;
                
            } else if (j == 'X')  {
                
                foo += 10;
                
            }  else if (j == 'V' && s.charAt(i-1) == 'I')  {         
                
                foo += 3;
                
            }  else if (j == 'V' && s.charAt(i-1) != 'I')  {
            
                foo += 5;
        
            }  else if (j == 'I')  {
            
                foo += 1;
            
            }

        }
        
	//returns foo, which is then printed out in main
        
       return foo; 
        
    }
    
}
